<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="theme-color" content="#1B2942">
        <title>Guide & Normes LMD — GNU</title>
        @vite(['resources/css/app.css', 'resources/js/app.js'])
    </head>
    <body class="guide-page">
        <header class="guide-header"><a class="brand" href="{{ route('login') }}" aria-label="Retour à la connexion GNU"><svg class="gnu-emblem" viewBox="0 0 48 48" aria-hidden="true"><rect x="4" y="8" width="40" height="4" rx="1"/><rect x="7" y="15" width="34" height="4" rx="1" opacity=".85"/><rect x="11" y="22" width="26" height="4" rx="1" opacity=".7"/><rect x="16" y="29" width="16" height="4" rx="1" opacity=".55"/><rect class="gnu-emblem-accent" x="21" y="36" width="6" height="4" rx="1"/></svg><span><strong>GNU</strong><small>Système académique LMD · Portail officiel</small></span></a><nav class="guide-nav" aria-label="Navigation du guide"><a href="{{ route('login') }}">Authentification</a><a class="is-current" href="{{ route('guide.lmd') }}">Guide & Normes LMD</a><a href="{{ route('support.registres') }}">Support & Registres</a></nav><span class="auth-user"><svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="8" r="3"/><path d="M5 20a7 7 0 0 1 14 0"/></svg></span></header>
        <main class="guide-content guide-reference">
            <div class="guide-breadcrumb"><span>République Universitaire</span><b>/</b><span>Cadre Juridique National</span><b>/</b><strong class="guide-code">DOC-LMD-2024-V4</strong><span class="guide-badge">✓ Texte Réglementaire d'Ordre Public</span></div>
            <section class="guide-hero"><div><p class="eyebrow guide-kicker">Référentiel académique officiel · Système LMD</p><h1>Guide Réglementaire & Normes d'Évaluation</h1><p>Règles communes d'organisation des enseignements universitaires, modalités de pondération du contrôle continu, barèmes de crédits ECTS et principes stricts de compensation des semestres.</p></div><div class="guide-action"><button type="button" onclick="window.print()">⇩ &nbsp; Télécharger le Guide PDF (A4)</button><span class="mono">Dernière homologation : Décret n° 2024-819<br>Version 4 · Applicable 2024-2025</span></div></section>
            <div class="guide-search"><span>⌕</span><input type="search" placeholder="Rechercher une règle, une formule, un seuil (ex: note éliminatoire, rattrapage, ECTS)..."><span class="mono">§ 05 chapitres répertoriés</span></div>
            <nav class="guide-summary" aria-label="Sommaire"><span>SOMMAIRE</span><a href="#architecture">1. Architecture & Crédits ECTS</a><a href="#evaluation">2. Pondération CC & Examens</a><a href="#compensation">3. Règles de Compensation</a><a href="#bareme">4. Barème & Mentions</a><a href="#jury">5. Délibérations du Jury</a></nav>

            <section class="guide-full-section" id="architecture"><div class="guide-section-heading"><span class="guide-rule"></span><div><p class="eyebrow">§ 01</p><h2>Architecture des Grades & Volume de Crédits ECTS</h2></div><span class="mono section-meta">NORME EUROPÉENNE ECTS</span></div><p class="section-lead">L'enseignement supérieur universitaire s'articule exclusivement autour des trois grades canoniques du système LMD. La validation repose sur l'accumulation de crédits transférables et capitalisables.</p><div class="grade-cards"><article><p class="eyebrow">Cycle 1</p><h3>Licence Fondamentale & Pro</h3><p>Acquisition des savoirs fondamentaux et méthodologiques pour graduer (L1, L2, L3).</p><strong>180 ECTS</strong><small class="mono">6 Semestres · 30 ECTS / semestre</small></article><article><p class="eyebrow">Cycle 2</p><h3>Master Recherche / Professionnel</h3><p>Approfondissement théorique, séminaires de recherche, projet tutoré et soutenance de mémoire.</p><strong>120 ECTS</strong><small class="mono">4 Semestres · 30 ECTS / semestre</small></article><article><p class="eyebrow">Cycle 3</p><h3>Doctorat & Thèse</h3><p>Travaux de recherche originaux, publications certifiées et soutenance publique de thèse.</p><strong>180 ECTS</strong><small class="mono">6 Semestres min. · Soutenance</small></article></div><div class="guide-note"><strong>ⓘ Principe intangible de l'Unité d'Enseignement (UE)</strong><span>Chaque semestre est divisé en UE majeures, complémentaires et transversales. Chaque UE possède un quota rigide de crédits ECTS.</span></div></section>

            <section class="guide-full-section" id="evaluation"><div class="guide-section-heading"><span class="guide-rule"></span><div><p class="eyebrow">§ 02</p><h2>Modalités d'Évaluation & Calcul des Notes</h2></div><span class="mono section-meta">ARTICLE LMD 14-8</span></div><p class="section-lead">Le contrôle des connaissances s'articule rigoureusement selon la nature de l'Unité d'Enseignement. Les épreuves expérimentales et théoriques sont pondérées.</p><div class="evaluation-grid"><div class="evaluation-cases"><article><strong>Cas 1 : Matières AVEC Travaux Pratiques (TP)</strong><div><span>Contrôle Continu (CC)<b>20%</b></span><span>Travaux Pratiques (TP)<b>30%</b></span><span>Session Normale (SN)<b>50%</b></span></div></article><article><strong>Cas 2 : Matières SANS Travaux Pratiques (Sans TP)</strong><div><span>Contrôle Continu Régulier (CC)<b>30%</b></span><span>Session Normale de l'Examen (SN)<b>70%</b></span></div></article></div><aside class="formula-card"><p class="eyebrow">Équations officielles de calcul</p><strong class="mono">Cas 1 — Avec travaux pratiques (TP)</strong><p class="mono">Note finale = (CC × 0.20) + (TP × 0.30) + (SN × 0.50)</p><strong class="mono">Cas 2 — Sans travaux pratiques</strong><p class="mono">Note finale = (CC × 0.30) + (SN × 0.70)</p><div class="warning-card">⚠ Note Éliminatoire & Redoublement Strict<br><small>Obtenir une note avec un pourcentage inférieur à 35% est éliminatoire.</small></div></aside></div></section>

            <section class="guide-full-section" id="compensation"><div class="guide-section-heading"><span class="guide-rule"></span><div><p class="eyebrow">§ 03</p><h2>Principes de Compensation, Capitalisation & Rattrapage</h2></div><span class="mono section-meta">STATUTS DE DÉLIBÉRATION</span></div><div class="principle-grid"><article><h3>1. Validation Directe d'UE</h3><p>Une unité d'enseignement est validée dès que la moyenne pondérée est supérieure ou égale à 10/20.</p><span class="mono valid-label">VALEUR UE</span></article><article><h3>2. Compensation Semestrielle</h3><p>La compensation s'applique au sein d'un même semestre si la moyenne générale est supérieure ou égale à 10/20.</p><span class="mono appeal-label">COMPENSÉ (VAL)</span></article><article><h3>3. Capitalisation & Transférabilité</h3><p>Les crédits ECTS associés à toute UE validée sont définitivement acquis et conservés.</p><span class="mono valid-label">ACQUIS DÉFINITIVE</span></article><article><h3>4. Deuxième Session (Rattrapage)</h3><p>L'étudiant qui n'a pas validé son semestre est tenu de se présenter aux épreuves de rattrapage.</p><span class="mono danger-label">SESSION 2 (SR)</span></article></div></section>

            <section class="guide-full-section" id="bareme"><div class="guide-section-heading"><span class="guide-rule"></span><div><p class="eyebrow">§ 04</p><h2>Barème Officiel de Notation & Échelle des Mentions</h2></div><span class="mono section-meta">GRILLE HARMONISÉE</span></div><p class="section-lead">Les délibérations universitaires convertissent la moyenne sur 20 en grades littéraux standardisés assortis d'une mention officielle.</p><div class="mention-table"><div class="mention-row mention-head"><span>Intervalle de moyenne</span><span>Grade ECTS</span><span>Mention portée au diplôme</span><span>Statut du crédit</span></div><div class="mention-row"><strong>16.00 à 20.00</strong><b>Grade A</b><span>Mention Très Bien</span><i>Crédits Accordés</i></div><div class="mention-row"><strong>14.00 à 15.99</strong><b>Grade B</b><span>Mention Bien</span><i>Crédits Accordés</i></div><div class="mention-row"><strong>12.00 à 13.99</strong><b>Grade C</b><span>Mention Assez Bien</span><i>Crédits Accordés</i></div><div class="mention-row"><strong>10.00 à 11.99</strong><b>Grade D</b><span>Mention Passable</span><i>Crédits Accordés</i></div><div class="mention-row mention-fail"><strong>00.00 à 09.99</strong><b>Grade F</b><span>Ajourné</span><i>Crédits Refusés</i></div></div></section>

            <section class="guide-full-section" id="jury"><div class="guide-section-heading"><span class="guide-rule"></span><div><p class="eyebrow">§ 05</p><h2>Procédure & Souveraineté du Jury Délibérant</h2></div><span class="mono section-meta">PROTOCOLE INSTITUTIONNEL</span></div><div class="jury-grid"><article>⚖ <strong>Souveraineté d'Appréciation</strong><p>Le jury de délibération apprécie souverainement les résultats, dans le respect du règlement.</p></article><article>▧ <strong>Procès-Verbal Signé</strong><p>Toute délibération donne lieu à un procès-verbal signé et archivé.</p></article><article>◷ <strong>Délais de Réclamation</strong><p>Les étudiants disposent d'un délai de 72 heures ouvrées suivant l'affichage officiel.</p></article></div><div class="guide-contact-banner"><span>ⓘ</span><p><strong>Une question d'interprétation ou un litige de délibération ?</strong><small>Pour tout recours gracieux relatif au calcul des moyennes, contactez la Cellule des Examens.</small></p><a href="{{ route('support.registres') }}">Registres & Contact UFR</a></div></section>
        </main>
        <footer class="guide-footer"><span class="footer-brand"><svg class="gnu-emblem" viewBox="0 0 48 48" aria-hidden="true"><rect x="4" y="8" width="40" height="4" rx="1"/><rect x="7" y="15" width="34" height="4" rx="1" opacity=".85"/><rect x="11" y="22" width="26" height="4" rx="1" opacity=".7"/><rect x="16" y="29" width="16" height="4" rx="1" opacity=".55"/><rect class="gnu-emblem-accent" x="21" y="36" width="6" height="4" rx="1"/></svg><strong>GNU — Gestion des Notes Universitaires</strong></span><span class="mono">Registre Certifié · © 2024-2025 République Universitaire</span></footer>
    </body>
</html>
