<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="theme-color" content="#1B2942">
        <title>Support & Registres Académiques — GNU</title>
        @vite(['resources/css/app.css', 'resources/js/app.js'])
    </head>
    <body class="support-page">
        <header class="support-header">
            <a class="brand" href="{{ route('login') }}" aria-label="Retour à la connexion GNU"><svg class="gnu-emblem" viewBox="0 0 48 48" aria-hidden="true"><rect x="4" y="8" width="40" height="4" rx="1"/><rect x="7" y="15" width="34" height="4" rx="1" opacity=".85"/><rect x="11" y="22" width="26" height="4" rx="1" opacity=".7"/><rect x="16" y="29" width="16" height="4" rx="1" opacity=".55"/><rect class="gnu-emblem-accent" x="21" y="36" width="6" height="4" rx="1"/></svg><span><strong>GNU</strong><small>Système académique LMD · Portail officiel</small></span></a>
            <nav class="support-nav" aria-label="Navigation principale"><a href="{{ route('login') }}">Authentification</a><a href="{{ route('guide.lmd') }}">Guide & Normes LMD</a><a class="is-current" href="{{ route('support.registres') }}"><svg class="nav-svg" viewBox="0 0 24 24" aria-hidden="true"><path d="M4 5h16v14H4zM8 9h8M8 13h8M8 17h5"/></svg>Support & Registres</a></nav><span class="auth-user"><svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="8" r="3"/><path d="M5 20a7 7 0 0 1 14 0"/></svg></span>
        </header>

        <main class="support-content">
            <div class="support-breadcrumb"><a href="{{ route('login') }}">Accueil</a><b>›</b><span>Système Licence-Master-Doctorat</span><b>›</b><strong>Support & Registres Académiques</strong><span class="registry-open"><i></i> Registre Central Délibératif Ouvert · Session 2024-2025</span></div>
            <section class="support-hero"><div><p class="eyebrow support-kicker">DÉLIBÉRATIONS · RECOURS · REGISTRES MATRICULAIRES</p><h1>Registres Académiques & Cellule de Support</h1><p>Consultation des registres officiels de notes, protocole de dépôt de réclamation post-délibération (délai légal de 72h) et assistance technique aux jurys et enseignants.</p></div><div class="support-actions"><button type="button" onclick="window.print()">⇩ &nbsp; Bordereau Réclamation (PDF)</button><a href="#formulaire-recours">✎ &nbsp; Déposer une Requête</a></div></section>

            <div class="deadline-alert"><b>!</b><div><strong>RÈGLE STRICTE DES DÉLAIS DE RÉCLAMATION DE NOTES</strong><p>Conformément au règlement LMD, les contestations de notes ou signalements d'omissions matérielles (erreur de report, absence injustifiée erronée « A ») doivent être soumises dans un délai strict de <span class="mono">72 heures ouvrées</span> suivant l'affichage officiel des procès-verbaux de délibération.</p></div></div>

            <div class="support-grid"><div class="support-main-column"><section class="registry-panel"><div class="support-panel-title"><div><span class="section-code mono">§ 01</span><h2>Consultation du Registre Centralisé des Notes</h2></div><span class="mono panel-label">ACCÈS DÉLIBÉRATIONS</span></div><p class="panel-intro">Vérifiez l'état d'enregistrement des procès-verbaux (PV), les publications par Unité d'Enseignement et les mentions portées au registre officiel de délibération.</p><div class="registry-filters"><label>Matricule étudiant<input data-registry-filter type="search" placeholder="Ex: 21A123"></label><label>Code unité (UE)<input data-registry-filter type="search" placeholder="Ex: INF301"></label><label>Cycle / niveau<select data-registry-filter><option value="">Licence 3 (L3)</option><option>L1</option><option>L2</option><option>L3</option><option>M1</option><option>M2</option><option>Doctorat</option></select></label></div><div class="registry-table-wrap"><table class="registry-table"><thead><tr><th>Réf. registre</th><th>UE & intitulé</th><th>Type matière</th><th>Date PV</th><th>Statut clôture</th></tr></thead><tbody><tr data-registry-row><td class="mono strong-code">REG-2024-L3-084</td><td><span class="mono">INF301</span> · Algorithmique Avancée<small>6 Crédits · 60h CM/TD</small></td><td><span class="table-tag">Avec TP<br>(20/30/50)</span></td><td class="mono muted-cell">08/09/2024</td><td><span class="table-status valid">● Scellé & Homologué</span></td></tr><tr data-registry-row><td class="mono strong-code">REG-2024-L3-085</td><td><span class="mono">INF305</span> · Systèmes d'Exploitation & Réseaux<small>6 Crédits · 60h CM/TD</small></td><td><span class="table-tag">Avec TP<br>(20/30/50)</span></td><td class="mono muted-cell">07/09/2024</td><td><span class="table-status appeal">○ Période Recours<br>(48h)</span></td></tr><tr data-registry-row><td class="mono strong-code">REG-2024-L3-086</td><td><span class="mono">MAT311</span> · Probabilités & Statistiques LMD<small>4 Crédits · Sans TP</small></td><td><span class="table-tag">Sans TP (30/70)</span></td><td class="mono muted-cell">06/09/2024</td><td><span class="table-status valid">● Scellé & Homologué</span></td></tr><tr data-registry-row><td class="mono strong-code">REG-2024-L3-089</td><td><span class="mono">ENG300</span> · Anglais Technique & Rédaction<small>2 Crédits · Transversale</small></td><td><span class="table-tag">Sans TP (30/70)</span></td><td class="mono muted-cell">05/09/2024</td><td><span class="table-status valid">● Scellé & Homologué</span></td></tr></tbody></table><p class="registry-empty" data-registry-empty hidden>Aucun registre ne correspond aux critères saisis.</p></div></section>

                    <section class="request-panel" id="formulaire-recours"><div class="request-heading"><div><p class="eyebrow">§ 02</p><h2>Dépôt d'une Requête de Délibération ou Rectification</h2></div><span class="eyebrow request-label">FORMULAIRE OFFICIEL</span></div><p class="request-intro">Ce formulaire permet aux étudiants et délégués de signaler une anomalie matérielle constatée sur le relevé de notes ou PV de session normale / rattrapage.</p><form class="request-form request-form-detailed" onsubmit="event.preventDefault(); this.querySelector('.request-success').hidden = false;"><label>Matricule universitaire *<input type="text" value="21A123" required></label><label>Nom complet de l'étudiant *<input type="text" placeholder="Ex: NJOCK Jean-Baptiste" required></label><label>Unité d'enseignement concernée *<select required><option>INF305 · Systèmes d'Exploitation</option><option>INF301 · Algorithmique Avancée</option></select></label><label>Composante contestée *<select required><option>Travaux Pratiques (TP - 30%)</option><option>Contrôle continu (CC - 20%)</option><option>Examen final (SN - 50%)</option></select></label><label>Note affichée / présumée<input type="text" placeholder="Affiché: 06/20 · Évalué: 14/20"></label><label class="request-full">Motif explicatif du recours académique *<textarea required placeholder="Décrivez succinctement l'anomalie : présence émargée lors du TP non prise en compte, copie d'examen non répertoriée ou erreur d'addition sur le relevé..."></textarea></label><div class="request-submit-row"><small>* Une décharge numérotée sous format <span class="mono">REC-2024-XXXX</span> est automatiquement émise.</small><button type="submit">◉ &nbsp; Transmettre au Secrétariat du Jury</button><small class="request-success" hidden>Requête enregistrée dans l'interface de démonstration.</small></div></form></section></div>

                <aside class="support-aside"><section class="support-card support-contact"><p class="eyebrow support-card-kicker">PERMANENCE JURY</p><h2>Cellule des Examens & Notes</h2><div class="contact-line"><span>▥</span><div><strong>Secrétariat Académique Central</strong><small>Bâtiment Administratif Décanat · Bureau 104</small></div></div><div class="contact-line"><span>◷</span><div><strong>Horaires d'ouverture des registres</strong><small class="mono">Lundi — Vendredi · 08h30 — 15h30</small></div></div><div class="contact-line"><span>✉</span><div><strong>Courriel Officiel d'Assistance</strong><small class="mono contact-email">support.lmd@univ-gnu.edu</small></div></div><div class="phone-line"><span>LIGNE TÉLÉPHONIQUE DÉDIÉE</span><strong>Poste Interne : #2410</strong><b>● Ligne Ouverte</b></div></section><section class="support-card"><p class="eyebrow">DOCUMENTS TYPES</p><h2>Documents & Registres Types</h2><a class="document-link" href="#formulaire-recours"><span>♧</span><span><strong>Bordereau de PV de Délibération</strong></span><small>PDF · 140 Ko</small></a><a class="document-link" href="#formulaire-recours"><span>♧</span><span><strong>Formulaire de Rectification Matérielle</strong></span><small>PDF · 95 Ko</small></a><a class="document-link" href="#formulaire-recours"><span>♧</span><span><strong>Fiche d'Émargement Travaux Pratiques</strong></span><small>XLSX · 65 Ko</small></a></section><section class="server-card"><p class="eyebrow">SERVEUR ACADÉMIQUE GNU</p><strong>● 100% Opérationnel</strong><p>Base de données scellée en lecture seule pour les PV validés. Synchronisation instantanée des saisies de contrôle continu.</p></section></aside></div>
        </main>
        <footer class="support-footer"><span class="footer-brand"><svg class="gnu-emblem" viewBox="0 0 48 48" aria-hidden="true"><rect x="4" y="8" width="40" height="4" rx="1"/><rect x="7" y="15" width="34" height="4" rx="1" opacity=".85"/><rect x="11" y="22" width="26" height="4" rx="1" opacity=".7"/><rect x="16" y="29" width="16" height="4" rx="1" opacity=".55"/><rect class="gnu-emblem-accent" x="21" y="36" width="6" height="4" rx="1"/></svg><strong>GNU — Gestion des Notes Universitaires</strong></span><span class="mono">Année Universitaire 2024-2025</span><a href="{{ route('support.registres') }}">Assistance & Support</a></footer>
    </body>
</html>
